server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5678/identity-service
    username: minhhieu
    password: minhhieu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true